name: GAE Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

defaults:
  run:
    working-directory: ./
jobs:
  job1:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: List directory
          run: ls
        - name: Install Dependencies
          run: pip install -r requirements.txt
        - name: Make Migrations
          run: python manage.py makemigrations
        - name: Make Migrations Encyclopedia
          run: python manage.py makemigrations encyclopedia
        - name: Migrate
          run: python manage.py migrate
