name: Deploy Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./
jobs:
  job1:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: List directory
          run: ls
