name: GAE Deploy

on:
  watch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./
jobs:
  job1:
    environment: production-gcloud
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    runs-on: ubuntu-latest
    name: Git Deploy job- A job to deploy django app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check Python Version
        run: python3 --version

      - name: Install Dependencies
        run: pip3 install -r requirements.txt
        
      - name: Collect Static
        run: python3 manage.py collectstatic
     
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
