# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production-gcloud

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to Google App Engine
        uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_name: ${{ secrets.PROJECT_NAME }}
