name: GAE Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./
jobs:
  job1:
    environment: production-gcloud
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    runs-on: ubuntu-latest
    name: Git Deploy job- A job to deploy django app
    steps:
      - id: GetCredentials
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: List directory
        run: ls
      - name: Check Python Version
        run: python3 --version
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      - name: Collect Static
        run: python3 manage.py collectstatic
